### PR TITLE
Escape 'rank' column in SQL queries since it is a reserverd keyword in mysql 8.0.2

### PR DESCRIPTION
**Pull request by mihajul**
Escape 'rank' column in SQL queries since it is a reserverd keyword in mysql 8.
Fixes issue #242

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mihajul Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-projects/spring-social&pullRequestId=262)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=spring-projects/spring-social&pullRequestId=262) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mihajul Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-projects/spring-social&pullRequestId=262)!

**Comment by maedabr** [comment]
Is this pull request will be merged soon?

**Comment by daniubi** [comment]
Merged quickly will be better.

**Pull request merged**
