### PR TITLE
Changing the OAuth2AuthenticationService to allow for an applicationUrl

### PR DESCRIPTION
**Pull request by cl4r1ty**
Pull request to address Issue #114

### CODE REVIEW

**Comment by damiancalabresi** [comment]
Hi, this pull request has never been merged. I use the 1.1.0.RELEASE version and still have the same bug, because the redirectUrl cannot be changed when you are behind a proxy server.

**Comment by cl4r1ty** [comment]
I would suggest updating your configuration to use ConnectionFactories instead of the older way of using the AuthenticationService. I closed this issue and PR due to not longer using this setup.

See https://github.com/spring-projects/spring-social-samples/blob/master/spring-social-showcase/src/main/java/org/springframework/social/showcase/config/SocialConfig.java as an example.

**Comment by damiancalabresi** [comment]
I'm using the SocialAuthenticationFilter to integrate Spring Social with Spring Security. 
Do you say it's not recommended? What should I do instead? Use the ProviderSigninController?

Thanks for your reply

**Comment by cl4r1ty** [comment]
I'd follow the newest spring-social-showcase example config which uses the Connect and SignIn controllers.

**Comment by damiancalabresi** [comment]
Thanks for your help, I will use this way (This implies many changes in my code). 
Probably the Spring Social Reference should be updated, because it recommends the SocialAuthenticationFilter when you have a Spring Security Context.

**Pull request closed without merging**
