### PR TITLE
SOCIAL-447: Fix OAuth2 redirect url when server is behind a proxy

### PR DESCRIPTION
**Pull request by jaffadog**
https://jira.spring.io/browse/SOCIAL-447

I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

When we are behind a proxy which is terminating SSL and forwarding
our server http rather than the original https or the original user
request, OAuth2AuthenticationService will incorrectly generate a
redirect_uri using the http scheme rather than https.  A similar issue
can occur if the proxy is doing port translation.  To correct this, we
are replacing the original approach, which is to use
HttpServletRequest.getRequestURL() with an approach that looks for and
uses X-Forwarded-Proto and X-Forwarded-Port request headers, which
should be inserted by the proxy.

### CODE REVIEW

**Comment by keyuls** [comment]
Which version of Spring-Social has this update?

**Comment by pivotal-issuemaster** [comment]
@jaffadog Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-projects/spring-social&pullRequestId=193)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=spring-projects/spring-social&pullRequestId=193) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jaffadog Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-projects/spring-social&pullRequestId=193)!

**Comment by darrachequesne** [comment]
Would it be possible to backport this fix in the 1.1.x branch please? 

Related: https://github.com/spring-projects/spring-social/issues/258

**Pull request merged**
