### PR TITLE
Upgrade thymeleaf 3

### PR DESCRIPTION
**Pull request by eddumelendez**
Fixes gh-207

### CODE REVIEW

**Comment by habuma** [comment]
I appreciate the help on migrating to Thymeleaf 3. For the time being, however, I'm going to follow Spring Boot's lead on this and stick with 2.1.5. When Spring Boot's dependencies shift to Thymeleaf 3, then I'll follow suit and merge this PR.

Also, if you've not yet signed the individual contributor agreement (https://cla.pivotal.io/), please do. It'd be greatly helpful for me when the time comes to merge. Thanks

**Comment by habuma** [comment]
Closing PR and then will immediately reopen, in hopes of triggering Travis CI.

**Comment by alek-sys** [comment]
Hi @habuma 
What do you think about the idea to extract Thymeleaf support (including dialect) from spring-social-web into a separate package spring-social-web-thymeleaf? It can be then split to thymeleaf2 / thymeleaf3 versions with dependencies on different TL versions. 

It has few advantages, actually:
1. It will be possible to create spring-social-web-thymeleaf2 and spring-social-web-thymeleaf3 now (based on @eddumelendez changes) and let people switch to version 3 if needed
2. spring-social-web will still use spring-social-web-thymeleaf2, so this is 100% backward compatible
3. It removes a direct dependency from spring-social-web to Thymeleaf. This will help people who don't use Thymeleaf but sill want to use Spring Social.
4. When Spring Boot will switch to TL 3 by default, the only change for Spring-Social will be dependency update from spring-social-web-thymeleaf2 to spring-social-web-thymeleaf3. 

If that sounds reasonable I can help with a pull request, I guess.

**Comment by wilkinsona** [comment]
Spring Boot 2.0 is going to upgrade to Thymeleaf 3

**Comment by theandrewlane** [comment]
Please merge :)

**Comment by habuma** [comment]
Rather than merge this PR directly, I've extracted the existing Thymeleaf 2 support into a separate module (as suggested by @alek-sys; thanks @alek-sys !) and create a new Thymeleaf 3 module with (most of) the changes from @eddumelendez. I had to change a few things, however, because it seems that the IContext passed around in ConnectedAttrProcessor cannot be cast to a Spring ApplicationContext, although it can be used to get the Spring ApplicationContext.

**Comment by alek-sys** [comment]
Awesome, thanks!

**Pull request closed without merging**
