### PR TITLE
An AuthenticationServiceException is wrongfully thrown when a user is already authenticated with the Authorization Server in SocialAuthenticationFilter

### LINKED ISSUE #194: An AuthenticationServiceException is wrongfully thrown when a user is already authenticated with the Authorization Server in SocialAuthenticationFilter
When a user is already authenticated with the Authorization Server (that is, when `SecurityContextHolder.getContext().getAuthentication()` return an authenticated `Authentication` object), `SocialAuthenticationFilter` wrongfully throws an `AuthenticationServiceException`. 

The error is in the method `attemptAuthService(final SocialAuthenticationService<?> authService, final HttpServletRequest request, HttpServletResponse response)` which when the user is already authenticated, returns `null`.

### PR DESCRIPTION
**Pull request by jebeaudet**
This fixes #194. I've already signed the contributor's agreement. Thanks!

### CODE REVIEW

**Comment by habuma** [comment]
Closing PR and then will immediately reopen, in hopes of triggering Travis CI.

**Comment by habuma** [comment]
Trying again...Closing PR and then will immediately reopen, in hopes of triggering Travis CI.

**Comment by jebeaudet** [comment]
I could push an extra commit and then squash it if you want.

**Comment by habuma** [comment]
I'm not sure if that would help. Closing the PR and reopening it worked for two other PRs, but not for this one and one other that I tried.

Gonna try once more. YOLO.

**Comment by jebeaudet** [comment]
Alright, let me know if I can do anything to help. Glad to see this project finally getting some attention ;)

**Pull request merged**
